//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopTomilov.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticleNumber { get; set; }
        public int ProductName { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductDiscountAmount { get; set; }
        public int ProductManufacturer { get; set; }
        public int ProductSupplier { get; set; }
        public int ProductCategory { get; set; }
        public int ProductDiscountNow { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhotoName { get; set; }
        public byte[] ProductPhoto { get; set; }
    
        public virtual ProductCategory ProductCategory1 { get; set; }
        public virtual ProductManufacture ProductManufacture { get; set; }
        public virtual ProductName ProductName1 { get; set; }
        public virtual ProductSupplier ProductSupplier1 { get; set; }
    }
}
